<?php global $title; ?>
<footer>
    <p>
        <a
            rel="cc:attributionURL dct:creator"
            property="cc:attributionName"
            href="https://linkedin.com/in/danyella-strikann"
            >Danyella Strikann</a
        >
        &nbsp;©&nbsp;2024&nbsp;•&nbsp;Ce site est sous license
        <a
            href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1"
            target="_blank"
            rel="license noopener noreferrer"
            style="display: inline-block; text-decoration: none">
            <span style="text-decoration: solid underline 1px"
                >Attribution-ShareAlike 4.0 International</span
            >
            <img
                alt="CC"
                style="
                    height: 22px !important;
                    margin-left: 3px;
                    vertical-align: text-bottom;
                "
                src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" />
            <img
                alt="BY"
                style="
                    height: 22px !important;
                    margin-left: 3px;
                    vertical-align: text-bottom;
                "
                src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" />
            <img
                alt="SA"
                style="
                    height: 22px !important;
                    margin-left: 3px;
                    vertical-align: text-bottom;
                "
                src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" />
        </a>
    </p>
</footer>

<script src="/assets/js/main.js"></script>
</body>
</html>
